Merchant Pay out
devscast/flexpay pull request #1
Opened 2024-10-13 21:25 UTC by rooneyi

2024-10-13 21:45 UTC, bernard-ng requested changes

2024-10-13 21:45 UTC, bernard-ng commented on src/Client.php
> -
pourquoi ce retrait ?
les autres fonctionnalités sont importantes, cette méthode est utiliser pour faire les payments

2024-10-13 21:45 UTC, bernard-ng commented on src/Client.php
> +    public function merchantPayOut(MerchantPayOutRequest $request): MerchantPayOutResponse
renommez en `payout` tout simplement
MerchantPayoutRequest => `PayoutRequest`
MerchantPayoutResponse => `PayoutResponse`

2024-10-13 21:45 UTC, bernard-ng commented on src/Environment.php
> +        };
Le lien du endpoint est `/api/rest/v1/merchantPayOutService` prière de suivre la documentation

- renomez la méthode en `getPayoutUrl`

2024-10-13 21:45 UTC, bernard-ng commented on src/Request/MerchantPayOutRequest.php
> +    private string $apiUrl = 'https://api.flexpay.cd/api/merchantPayOutService';
retirez ceci car déjà disponible dans le class `Environment` 
la `Request` est un DTO elle représente uniquement les données, pas de logique ici
car il sera difficile pour les utilisateurs de la libraire d'instancier cette class

2024-10-13 21:45 UTC, bernard-ng commented on src/Request/MerchantPayOutRequest.php
> +        $this->client = HttpClient::create();
à retirer, prière de suivre l'implémentation des autres fonctionnalités

2024-10-13 21:45 UTC, bernard-ng commented on src/Request/MerchantPayOutRequest.php
> +        public int $type = 1,
1 : mobile money.
2 : carte bancaire

on peut créer un value object pour cette valeur `TransactionType`

2024-10-13 21:45 UTC, bernard-ng commented on src/Request/MerchantPayOutRequest.php
> +            'callbackUrl' => $this->callbackUrl,
l'authorizaton manque dans le payload

2024-10-13 21:45 UTC, bernard-ng commented on src/Request/MerchantPayOutRequest.php
> +    }
à retirer la communication http se fait dans la class `Client`

2024-10-13 21:45 UTC, bernard-ng commented on src/Response/MerchantPayOutResponse.php
> +    }
class à renommer en `PayoutResponse`, les classes response représentent les données fournis par l'API, il y a donc aucune logique ici

il s'agit d'un simple DTO, se référer à la documentation pour savoir quel propriétés rajouter ici

2024-10-13 21:45 UTC, bernard-ng commented on composer.json
> +      "ext-http": "*"
à retirer, il n'y a rien à changer dans ce fichier

2024-10-15 11:59 UTC, bernard-ng requested changes

2024-10-15 11:59 UTC, bernard-ng commented on src/Data/TransactionType.php
> +}
ceci peut être une énumération (\BackedEnum<int>)

2024-10-15 11:59 UTC, bernard-ng commented on src/Environment.php
> +            self::LIVE => ': http://ip:port/api/rest/v1/merchantPayOutService',
idem ici, avec getBaseUrl

2024-10-15 11:59 UTC, bernard-ng commented on src/Request/PayoutRequest.php
> +            'Authorization' => $this->credentials->token,
authorization != Authorization

`'authorization' => sprintf('Bearer %s', $this->credentials->token)`

2024-10-15 14:39 UTC, bernard-ng commented
@rooneyi as-tu lancé les tests en local avant de push ?

2024-10-15 14:41 UTC, rooneyi commented
oui ,tout est bon mais je ne sais pas pourquoi on dit qu'il y'a des conflits

2024-10-15 14:43 UTC, bernard-ng approved these changes
après cette correction ajoute les tests et je vais merge

2024-10-15 14:43 UTC, bernard-ng commented on src/Data/TransactionType.php
> +    case MOBILE_MONEY = 1;
case MOBILE = 0;

2024-10-15 14:43 UTC, bernard-ng commented on src/Data/TransactionType.php
> +    case BANK_CARD = 2;
case CARD = 1;

2024-10-15 14:43 UTC, bernard-ng commented on src/Environment.php
> +            self::LIVE => 'http://ip:port/api/rest/v1/merchantPayOutService',
https://backend.flexpay.cd/api/rest/v1

2024-10-15 14:43 UTC, bernard-ng commented on src/Environment.php
> +            self::LIVE => 'http://ip:port/api/rest/v1/merchantPayOutService',
url de payout pour les deux environnement !

sprintf('%s/merchantPayOutService', $this->getBaseUrl())

2024-10-15 14:44 UTC, bernard-ng commented
> oui ,tout est bon mais je ne sais pas pourquoi on dit qu'il y'a des conflits

je vais régler le conflit après, il y a eu une mise à jour entre-temps

2024-10-15 14:44 UTC, rooneyi commented
D'accord

2024-10-16 08:48 UTC, bernard-ng requested changes

2024-10-16 08:48 UTC, bernard-ng commented on src/Request/PayoutRequest.php
> +        public string $telephone,
phone

2024-10-16 08:48 UTC, bernard-ng commented on src/Request/PayoutRequest.php
> +        public Credential $credentials,
Ceci ne doit pas être dans le constructeur, réfères toi aux autres classes pour faire la même chose

2024-10-16 08:48 UTC, bernard-ng commented on src/Request/PayoutRequest.php
> +        public TransactionType $type,
Ajoute la Valeur par défaut MOBILE

2024-10-16 08:48 UTC, bernard-ng commented on src/Request/PayoutRequest.php
> +            'merchant' => $this->merchant,
À corriger, Le marchant est disponible uniquement sur le credential

2024-10-16 08:48 UTC, bernard-ng commented on tests/ClientTest.php
> +            telephone: '243123456789',
Téléphone en phone 
Creditials à retirer

2024-10-16 08:48 UTC, bernard-ng commented on tests/ClientTest.php
> +
Espacement inutile lance "vendor/bin/ecs --fix" avant de faire un push

2024-10-16 21:26 UTC, bernard-ng approved these changes

2024-10-16 22:10 UTC, merged